name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master
      - test
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set branch variable
        run: echo "DEPLOY_PATH=$( [ '${{ github.ref_name }}' = 'better-ui' ] && echo 'better-ui' || echo '.')" >> $GITHUB_ENV

      - name: Install, build, and upload site
        uses: withastro/action@v3
        with:
          path: . # The root location of your Astro project
          node-version: 20
          package-manager: pnpm@latest

      - name: Move output to correct directory
        run: |
          mkdir -p public/${DEPLOY_PATH}
          mv dist/* public/${DEPLOY_PATH}/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'public'

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
